#%RAML 1.0
title: My-API
version: v1
baseUri: http://localhost:8081
/displayDate:
  get:
    description: Display date 
    responses:
      200:
        body:
          application/xml:
            example: !include date-example.json